"""empty message

Revision ID: 02751680e574
Revises: 56e1e286f6ce
Create Date: 2022-09-03 23:35:13.425157

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '02751680e574'
down_revision = '56e1e286f6ce'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_videos_publish_datetime'), 'videos', ['publish_datetime'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_videos_publish_datetime'), table_name='videos')
    # ### end Alembic commands ###
