"""empty message

Revision ID: ca4ee292dcac
Revises: 4cfca3758363
Create Date: 2022-09-03 09:18:18.463496

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ca4ee292dcac'
down_revision = '4cfca3758363'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('videos', sa.Column('video_id', sa.String(length=120), nullable=False))
    op.add_column('videos', sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True))
    op.add_column('videos', sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True))
    op.create_unique_constraint(None, 'videos', ['video_id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'videos', type_='unique')
    op.drop_column('videos', 'updated_at')
    op.drop_column('videos', 'created_at')
    op.drop_column('videos', 'video_id')
    # ### end Alembic commands ###
