"""empty message

Revision ID: 56e1e286f6ce
Revises: ca4ee292dcac
Create Date: 2022-09-03 11:30:34.436758

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '56e1e286f6ce'
down_revision = 'ca4ee292dcac'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('videos', 'title',
               existing_type=mysql.VARCHAR(charset='utf8mb4', collation='utf8mb4_bin', length=120),
               type_=sa.String(length=1024),
               existing_nullable=True)
    op.alter_column('videos', 'description',
               existing_type=mysql.VARCHAR(charset='utf8mb4', collation='utf8mb4_bin', length=120),
               type_=sa.String(length=2048),
               existing_nullable=True)
    op.alter_column('videos', 'publish_datetime',
               existing_type=mysql.VARCHAR(charset='utf8mb4', collation='utf8mb4_bin', length=120),
               type_=sa.DateTime(),
               existing_nullable=True)
    op.alter_column('videos', 'thumbnail_url',
               existing_type=mysql.VARCHAR(charset='utf8mb4', collation='utf8mb4_bin', length=100),
               type_=sa.String(length=2048),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('videos', 'thumbnail_url',
               existing_type=sa.String(length=2048),
               type_=mysql.VARCHAR(charset='utf8mb4', collation='utf8mb4_bin', length=100),
               existing_nullable=True)
    op.alter_column('videos', 'publish_datetime',
               existing_type=sa.DateTime(),
               type_=mysql.VARCHAR(charset='utf8mb4', collation='utf8mb4_bin', length=120),
               existing_nullable=True)
    op.alter_column('videos', 'description',
               existing_type=sa.String(length=2048),
               type_=mysql.VARCHAR(charset='utf8mb4', collation='utf8mb4_bin', length=120),
               existing_nullable=True)
    op.alter_column('videos', 'title',
               existing_type=sa.String(length=1024),
               type_=mysql.VARCHAR(charset='utf8mb4', collation='utf8mb4_bin', length=120),
               existing_nullable=True)
    # ### end Alembic commands ###
